Industrial IoT PR
microsoft/WhatTheHack pull request #172
Opened 2021-02-01 22:36 UTC by RyanTBerry

2021-02-02 23:48 UTC, gfilicetti reviewed
The lectures presentation should live in the Coach folder at the top level, you can call it "Lectures.pptx" or whatever you want, but it shouldn't live on the Students side of the house. (don't forget to update Coach/README.md to the new location).

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-02.md
> +**[Home](README.md)** - [Next Challenge >](./Challenge-03.md)
Need a previous link

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-03.md
> +**[Home](README.md)** - [Next Challenge >](./Challenge-04.md)
Need a previous link

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-05.md
> +[< Previous Challenge](./Challenge-04.md) - **[Home](README.md)** - [Next Challenge >](./Challenge-05.md)
Next link needs to be to Challenge 6, currently goes to itself

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-02.md
> + - Options for OPC Simulators -- first 2 are VM-based options
Remove bullet, should be a like line 6

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-02.md
> +## Tips (optional)
Remove "(optional)" here and in all subheadings, it was only meant for our templates.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-02.md
> +## Advanced Challenges (Optional)
Delete this line completely

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-01.md
> +## Tips (optional)
Remove from line 19 to end of file.... we should not have empty sections.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/Challenge-03.md
> +## Tips (optional)
remove optional

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/README.md
> +## Repository Contents
Don't need repository contents in the coach's guide root README since we already have it in the main README

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/README.md
> +- Challenge 4: **[Route messages and do time-series analysis](Student/Challenge-04.md)** **RYAN/AMIT**
You  need to remove everyone's name assignments on the challenges! eg: this line has **RYAN/AMIT**

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-01.md
> +1. IoT Hub created
Please make success criteria here and in the other challenges a regular, unordered bullet list. Unless they have to be completed in a certain order let's leave the numbers out of it.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-04.md
> +To compete this lab successfully, you need to finish the following tasks:
Remove this line 22, it is redundant, just give us a bullet list under the header Success Criteria

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-04.md
> +• Stand up Azure Time Series Insight Instance
This is not valid markdown for bullets and does not render. Use the '-' character for bullets.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-05.md
> +  - triggering actions and initiating workflows such as creating alerts, feeding information to a reporting tool, or storing transformed data in a data lake for later use
The sentence in these bullets should be capitalized

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-06.md
> +## Advanced Challenges
Need to be consistent... either put the "(optional)" on Advanced Challenges or remove it from the subtitles in the earlier challenges.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-07.md
> +- A `SSH` client installed. On Windows, this is available out-of-the-box in recent builds of Windows 10 and in the Windows Subsystem for Linux (both 1 and 2). You can also download a simple client if
SSH in ssh client should be monospaced, it isn't really a variable name or command.... I would just call it an 'ssh client' or use uppercase SSH if you wish.

Same applies to the rest of this file... just use ssh in regular text, no backticks.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Student/Challenge-07.md
> +## Advanced Challenges
Same comment here as before, make it consistent..... either put "(optional)" on all of them or none of them.

2021-02-02 23:48 UTC, gfilicetti commented on 029-IoTEdge/Coach/README.md
> ++ [Slide Deck to use for Delivery](../Student/assets/IoTHub_Edge.pptx)
Remove the +, I wouldn't make this a bullet, looks out of place.

2021-02-08 23:15 UTC, jrzyshr requested changes
Gino caught most of the things I caught.  I have a few additional notes here I'd like to request changed:

1) Remove all the "optional" tags from the headers as they were meant to be optional for the author to include...  not optional for the attendees to read/complete!
2) You have placed the PPTX for lectures in the /Student/assets folder.  The PPTX should be moved to the /Coach folder.  Remove the /Student/assets folder.
3) You have /Coach/assets folder.  This is the proper place for the image files you use in the MD pages.  However, I assume the .json files are solution files.   I would create a new /Coach/Solutions folder and move the .json files to it.
4) This is an optional recommendation (I won't require this for approval).  The Challenge-XX.md files in /Coach should be renamed to Solution-XX.md.  This would obvious require you to update all the links in /Coach/README.md and all the navigation links in each MD file.

2021-02-08 23:16 UTC, gfilicetti requested changes
Requesting changes from my comments.

2021-02-16 16:43 UTC, OrrinEdenfield commented
I've made requested changes to both coach and student guides for Challenge 5.

2021-02-18 13:38 UTC, OrrinEdenfield commented
More changes made. @RyanTBerry, @amitagrawal09, @lokijota Please review.

2021-02-18 16:47 UTC, RyanTBerry commented
Will do a new PR with changes

2021-02-18 16:52 UTC, closed without merging