Updates to IntroToKubernetes Ch03
microsoft/WhatTheHack pull request #207
Opened 2021-03-26 15:26 UTC by larryclaman

Made the following edits:
- Cleaned up / simplified language
- Provided links to reference documentation so that students don't need to do an internet search 'treasure hunt'
- Removed references to the Kubernetes Dashboard, as it has been deprecated in conjunction with AKS (see https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard)

cc'ing @gfilicetti and @micya as they were the two most recent contributors to the Kubernetes hack content.

2021-05-18 03:07 UTC, gfilicetti requested changes
quick typo fix and we're done. FYI @jrzyshr .

2021-05-18 03:07 UTC, gfilicetti commented on 001-IntroToKubernetes/Coach/03-k8sintro.md
> +		- This show show three nodes, but it will not show the availability zone.
@larryclaman you have a slight typo in this sentence: "show show"

2021-05-18 03:28 UTC, jrzyshr reviewed
Great stuff!  One minor request.

2021-05-18 03:28 UTC, jrzyshr commented on 001-IntroToKubernetes/Coach/03-k8sintro.md
> +    - To see the availability zone, run:  `kubectl get nodes -o custom-columns=NAME:'{.metadata.name}',REGION:'{.metadata.labels.topology\.kubernetes\.io/region}',ZONE:'{metadata.labels.topology\.kub
This is a spoonfeed IMO.  I think stick it in the coach's guide.

Personally, my go to here is to use 'kubectl describe node <nodename>' and let the students explore what data comes back.  They can google the fancy command that parses out just the zone #.  NO ONE will ever remember that as a takeaway from the hack! 

If you feel strongly about putting a pointer here, then go with 'describe node' and put a comment asking the student to review/explore the data that comes back.

2021-05-18 03:30 UTC, gfilicetti commented on 001-IntroToKubernetes/Coach/03-k8sintro.md
> +    - To see the availability zone, run:  `kubectl get nodes -o custom-columns=NAME:'{.metadata.name}',REGION:'{.metadata.labels.topology\.kubernetes\.io/region}',ZONE:'{metadata.labels.topology\.kub
I agree with Peter... I don't see a reason to spoon feed them off the jump. Give it as a nugget to the coach to use if the students get stuck.

2021-05-19 12:49 UTC, larryclaman commented on 001-IntroToKubernetes/Coach/03-k8sintro.md
> +    - To see the availability zone, run:  `kubectl get nodes -o custom-columns=NAME:'{.metadata.name}',REGION:'{.metadata.labels.topology\.kubernetes\.io/region}',ZONE:'{metadata.labels.topology\.kub
Peter & Gino:  Maybe our changes are out of sync; The updates you're noting are only in the coach guide.

2021-05-20 17:07 UTC, gfilicetti approved these changes

2021-05-20 17:09 UTC, gfilicetti commented
@larryclaman I'm good to go with your latest edits, and you're right the spoon feeding peter pointed out is already in the Coach's guide, sorry about that.

However you need to sync with upstream and resolve the conflicts that exist. After that i can push the button on this.

2021-05-20 19:55 UTC, larryclaman commented
@gfilicetti conflicts resolved.  should be good to go.

2021-05-20 23:07 UTC, merged