072-DataScienceInFabric
microsoft/WhatTheHack pull request #883
Opened 2024-07-31 16:11 UTC by juanlldc

Creating pull request with completed hack, having implemented the initial changes requested by Peter Laudati.

2024-11-15 01:01 UTC, Whowong reviewed
Please see the comments in my initial passthrough

2024-11-15 01:01 UTC, Whowong commented on 072-DataScienceInFabric/Student/Challenge-04.md
> +You have generated a set of predictions with the simulated data and have saved them as a delta table, making them available to create a PowerBI report
Please review and update success criteria based on the guidance

2024-11-15 01:01 UTC, Whowong commented on 072-DataScienceInFabric/Student/Challenge-04.md
> +Notebook sections:
Noting here similar feedback about instructions vs challenges

2025-01-06 21:50 UTC, kriation requested changes
The only change requested is the URL in the shell script.

2025-01-06 21:50 UTC, kriation commented on 072-DataScienceInFabric/Student/Resources/deployhack.sh
> +wget https://raw.githubusercontent.com/pradeepsingla87/WhatTheHack/xxx-DataScience_In_MicrosoftFabric/072-DataScienceInFabric/Student/Resources/heartdata.csv
@pradeepsingla87 @juanlldc @lesantana, should the URL for the location of the CSV reflect the WTH repository?

2025-01-06 22:31 UTC, Whowong commented on 072-DataScienceInFabric/Student/Challenge-00.md
> +To get started, download and unzip the Resources folder [here](https://aka.ms/FabricdsWTHResources). This folder contains the notebooks you will be working with, as well as a shell script that you wi
will resolve post publish

2025-01-06 22:32 UTC, Whowong commented on 072-DataScienceInFabric/Coach/Solution-00.md
> +In Challenge 0 on the student guide, students are instructed to download the Resources folder [here](https://aka.ms/FabricdsWTHResources). This folder contains the notebooks students will be working
will be resolved post publish

2025-01-06 22:32 UTC, Whowong commented on 072-DataScienceInFabric/Student/Resources/deployhack.sh
> +wget https://raw.githubusercontent.com/pradeepsingla87/WhatTheHack/xxx-DataScience_In_MicrosoftFabric/072-DataScienceInFabric/Student/Resources/heartdata.csv
Spoke with Juan and this will be updated post publish

2025-01-06 22:32 UTC, Whowong approved these changes

2025-01-07 20:32 UTC, kriation approved these changes

2025-01-07 21:24 UTC, merged